name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: knoxbsd/beastci@9e1ddaaa794f1752ccacff5ee00d96542e752776
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
