name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: knoxbsd/beastci@de52aab015c0fcf81685a0d90528c37c730186d9
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
