name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Save Key
      run: echo "${{ secrets.SSHKEY }}" > key
    - name: Change Permissions
      run: chmod 0600 key
    - name: Log in
      run: ssh -i key -o StrictHostKeyChecking=no knoxbsd@freebsd.number1engineering.com uname -a
    - uses: knoxbsd/beastci@de52aab015c0fcf81685a0d90528c37c730186d9
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
