name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: knoxbsd/beastci@8255feb139cf589dae2b26c6629fe9b1999f8a34
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
