name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: public-demo

    steps:
    - uses: actions/checkout@v3
    - uses: knoxbsd/beastci@45a9260cffb94d476011189b0c6d02295c1be099
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
