name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: IPv6 Check
      run: ping -c1 -6 google.com
    - uses: knoxbsd/beastci@b9168e2c2e61bf12a50944e9a8a60f1ac85957fc
      name: Build in FreeBSD Jail
      with: 
        command: make
        sshkey: ${{ secrets.SSHKEY }}
